package com.airi.assistant.brain

import com.airi.core.chain.AgentGoal
import com.airi.core.chain.PlanStep

object GoalBuilder {

    fun build(dto: PlanDto): AgentGoal {

        val steps = dto.steps.map { step ->
            when (step.action) {
                "click" -> PlanStep.Click(step.id)
                "scroll" -> PlanStep.ScrollForward()
                "wait" -> PlanStep.WaitFor(step.id)
                else -> PlanStep.Click(step.id)
            }
        }

        return AgentGoal(
            goalId = "goal_${System.currentTimeMillis()}",
            description = "Generated by AIRI",
            steps = steps
        )
    }
}
