package com.airi.assistant.ai

import android.util.Log
import com.airi.assistant.crash.OrchestratorCrashReporter
import com.airi.assistant.domain.logging.LoggingService
import com.airi.assistant.telemetry.AgentTelemetryEvent
import com.airi.assistant.telemetry.PrivacyTelemetryReporter
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch

/**
 * InferenceWatchdog — monitors LlamaManager JNI inference calls for hangs
 * and excessive latency.
 *
 * ── PROBLEM ───────────────────────────────────────────────────────────────
 *
 *   llama.cpp token generation runs on a dedicated single-threaded dispatcher
 *   ([llamaDispatcher]) protected by a Mutex. If the JNI call hangs (model
 *   load race, OOM in native heap, NDK signal), the dispatcher thread blocks
 *   indefinitely — the app appears frozen without any logcat output.
 *
 * ── DETECTION ────────────────────────────────────────────────────────────
 *
 *   The watchdog tracks:
 *     - [InferenceHeartbeat] updates published by LlamaManager on each token
 *     - The elapsed time since the last token was produced
 *
 *   If no heartbeat arrives within [STUCK_THRESHOLD_MS]:
 *     1. A [StuckAlert] is emitted via [alerts] StateFlow
 *     2. A crash report is filed via [OrchestratorCrashReporter]
 *     3. Telemetry is emitted if opted-in
 *     4. If [autoCancelOnStuck] is true, [onStuckCallback] is invoked
 *
 * ── LIFECYCLE ────────────────────────────────────────────────────────────
 *
 *   Call [startInference] before each llama.cpp call.
 *   Call [heartbeat] on each generated token.
 *   Call [stopInference] when the inference call returns (success or failure).
 *   Call [start] once from Application.onCreate() to launch the monitor loop.
 */
class InferenceWatchdog(
    private val crashReporter:     OrchestratorCrashReporter,
    private val telemetry:         PrivacyTelemetryReporter,
    private val autoCancelOnStuck: Boolean       = false,
    private val onStuckCallback:   (() -> Unit)? = null
) {

    private val TAG   = "InferenceWatchdog"
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    // ── State ─────────────────────────────────────────────────────────────────

    data class StuckAlert(
        val inferenceId:  String,
        val stuckForMs:   Long,
        val lastTokenMs:  Long,
        val tokenCount:   Int
    )

    private val _alerts = MutableStateFlow<StuckAlert?>(null)
    val alerts: StateFlow<StuckAlert?> = _alerts.asStateFlow()

    @Volatile private var inferenceId    = ""
    @Volatile private var lastHeartbeat  = 0L
    @Volatile private var inferenceStart = 0L
    @Volatile private var tokenCount     = 0
    @Volatile private var isInferring    = false

    private var monitorJob: Job? = null

    // ── Public API ────────────────────────────────────────────────────────────

    /** Start the periodic monitor loop. Call once from Application.onCreate(). */
    fun start() {
        if (monitorJob?.isActive == true) return
        monitorJob = scope.launch {
            LoggingService.info(TAG, "AIRI_PROOF INFERENCE_WATCHDOG STARTED threshold=${STUCK_THRESHOLD_MS}ms")
            while (isActive) {
                delay(SCAN_INTERVAL_MS)
                scan()
            }
        }
    }

    /**
     * Signal that an inference call has begun.
     * @param id Unique identifier for this inference request (e.g. request UUID).
     */
    fun startInference(id: String) {
        inferenceId    = id
        inferenceStart = System.currentTimeMillis()
        lastHeartbeat  = inferenceStart
        tokenCount     = 0
        isInferring    = true
        Log.d(TAG, "AIRI_PROOF INFERENCE_WATCHDOG START id=$id")
    }

    /**
     * Call on each token generated by llama.cpp.
     * Resets the watchdog timer so it knows inference is still alive.
     */
    fun heartbeat() {
        lastHeartbeat = System.currentTimeMillis()
        tokenCount++
    }

    /**
     * Signal that inference has completed (success or failure).
     * Clears the watched state.
     */
    fun stopInference() {
        val elapsed = if (inferenceStart > 0L) System.currentTimeMillis() - inferenceStart else 0L
        Log.d(TAG, "AIRI_PROOF INFERENCE_WATCHDOG STOP id=$inferenceId elapsed=${elapsed}ms tokens=$tokenCount")
        isInferring    = false
        inferenceId    = ""
        inferenceStart = 0L
        lastHeartbeat  = 0L
        tokenCount     = 0
        _alerts.value  = null
    }

    /** Report current inference latency metrics for observability consumers. */
    fun currentMetrics(): InferenceMetrics? {
        if (!isInferring) return null
        val now = System.currentTimeMillis()
        return InferenceMetrics(
            inferenceId    = inferenceId,
            elapsedMs      = now - inferenceStart,
            timeSinceToken = now - lastHeartbeat,
            tokenCount     = tokenCount
        )
    }

    /** Stop the watchdog entirely. Should only be called on app shutdown. */
    fun shutdown() {
        scope.cancel()
        Log.i(TAG, "AIRI_PROOF INFERENCE_WATCHDOG SHUTDOWN")
    }

    // ── Monitor Loop ──────────────────────────────────────────────────────────

    private fun scan() {
        if (!isInferring || lastHeartbeat == 0L) return
        val now      = System.currentTimeMillis()
        val stuckFor = now - lastHeartbeat

        if (stuckFor < STUCK_THRESHOLD_MS) return

        val alert = StuckAlert(
            inferenceId  = inferenceId,
            stuckForMs   = stuckFor,
            lastTokenMs  = lastHeartbeat,
            tokenCount   = tokenCount
        )
        _alerts.value = alert

        LoggingService.warn(TAG, "AIRI_PROOF INFERENCE_WATCHDOG STUCK id=$inferenceId stuckFor=${stuckFor}ms tokens=$tokenCount")

        crashReporter.reportManual(
            component = "inference_watchdog",
            errorTag  = "LLM_INFERENCE_STUCK",
            message   = "llama.cpp stuck for ${stuckFor}ms (id=$inferenceId tokens=$tokenCount)"
        )

        telemetry.report(
            AgentTelemetryEvent.AgentFailed(
                agentId = "llm_backend",
                reason  = "INFERENCE_STUCK_${stuckFor}ms"
            )
        )

        if (autoCancelOnStuck) {
            LoggingService.warn(TAG, "AIRI_PROOF INFERENCE_WATCHDOG AUTO_CANCEL id=$inferenceId")
            runCatching { onStuckCallback?.invoke() }
        }
    }

    // ── Types ─────────────────────────────────────────────────────────────────

    data class InferenceMetrics(
        val inferenceId:    String,
        val elapsedMs:      Long,
        val timeSinceToken: Long,
        val tokenCount:     Int
    ) {
        val tokensPerSecond: Double
            get() = if (elapsedMs > 0) tokenCount * 1000.0 / elapsedMs else 0.0
    }

    companion object {
        private const val SCAN_INTERVAL_MS  = 10_000L
        private const val STUCK_THRESHOLD_MS = 30_000L
    }
}
