package com.airi.assistant.ai.prompt

import android.util.Log
import com.airi.assistant.ai.PerformanceMode
import com.airi.assistant.ai.QueryType
import com.airi.assistant.ai.context.ContextBudget
import com.airi.assistant.ai.prompt.budget.ContributorBudgetPolicy

/**
 * DynamicPromptEngine — assembles the final system prompt before every model
 * execution, combining all available context sources with priority ranking.
 *
 * ── ASSEMBLY ORDER (highest priority → lowest) ────────────────────────────────
 *
 *   1. [agentModePrompt]  — the agent-mode persona (e.g. "You are AIRI…")
 *   2. [ragContextBlock]  — semantic memory retrieved from prior conversation
 *   3. [skillBlock]       — active skill instructions (skill-awareness)
 *   4. [toolBlock]        — tool schema descriptions (tool-awareness)
 *   5. [qualityRules]     — response quality constraints
 *   6. [customPrompt]     — user-defined system prompt override
 *
 * ── CONTEXT RANKING ───────────────────────────────────────────────────────────
 *
 *   The engine applies a token budget to the injected context:
 *     - RAG block is trimmed to [maxRagTokens] before injection so a long
 *       memory chain never overflows the model's context window.
 *     - If [ragContextBlock] is empty the slot is skipped — no blank sections.
 *     - Skill and tool blocks are omitted in FAST performance mode to keep
 *       prompt short and inference latency low.
 *
 * ── MEMORY COMPRESSION ───────────────────────────────────────────────────────
 *
 *   When [memorySummary] is provided (generated by [ConversationSummarizer]),
 *   it is injected immediately after the RAG block as a compact transcript of
 *   older turns that exceeded the LLM's context window. This gives the model
 *   continuity without replaying full history.
 *
 * ── INTEGRATION ───────────────────────────────────────────────────────────────
 *
 *   [ChatViewModel.buildDynamicSystemPrompt] calls [build] and passes the
 *   result to [AgentLoop.run] as the [systemPrompt] parameter.
 *   [ServiceLocator.dynamicPromptEngine] holds the singleton.
 *
 * ── PROOF LOGGING ─────────────────────────────────────────────────────────────
 *
 *   Logs AIRI PROMPT_BUILT with the slot sizes so the engineering team
 *   can verify injection without a debugger.
 */
object DynamicPromptEngine {

    private const val TAG = "DynamicPromptEngine"

    /**
     * Estimated chars-per-token ratio (conservative: 4 chars / token).
     * Matches [PromptCompressor.estimateTokens] and [EmbeddingService.formatContextWithBudget].
     */
    private const val CHARS_PER_TOKEN = 4

    /**
     * SPRINT 1 migration note: DEFAULT_MAX_RAG_TOKENS was the sole RAG cap before Sprint 1.
     * It is now the fallback when no live ContextBudget is available (e.g. before model load).
     * After model load, the effective RAG budget scales with contextBudget.ragTokens:
     *   nCtx=1536  → ragTokens=92   (was: 512)
     *   nCtx=4096  → ragTokens=270  (was: 512)
     *   nCtx=32768 → ragTokens=1024 (was: 512, now clamped at 1024)
     */
    private const val DEFAULT_MAX_RAG_TOKENS = 512

    // ── Public API ─────────────────────────────────────────────────────────────

    /**
     * Build the final, fully-assembled system prompt for one LLM generation.
     *
     * SPRINT 1: Accepts an optional [contextBudget] derived from LlamaNative.getNCtx()
     * via LlamaManager.contextBudget. When provided, RAG and summary token/char caps
     * scale with the loaded model's actual nCtx rather than the former hardcoded
     * DEFAULT_MAX_RAG_TOKENS=512. Explicit [maxRagTokens] overrides the budget when
     * the caller needs a specific cap (e.g. buildFast() uses 128 tokens).
     *
     * @param agentModePrompt  The agent-mode persona base string.
     * @param responseStyle    User-selected response style ("concise"/"detailed"/other).
     * @param customPrompt     User-defined system prompt override (may be blank).
     * @param performanceMode  Current performance mode — affects verbosity & block inclusion.
     * @param queryType        Detected query type for style hints.
     * @param ragContextBlock  Pre-retrieved semantic memory block (from RagRetriever).
     *                         Empty string → slot is omitted.
     * @param memorySummary    Optional compressed summary of older turns
     *                         (from ConversationSummarizer). Empty → omitted.
     * @param skillBlock       Skill description block from SkillRegistry.
     *                         Empty → omitted.
     * @param toolBlock        Tool description block from ToolRegistry.
     *                         Empty → omitted.
     * @param maxRagTokens     Explicit token cap for the RAG block. When -1 (default),
     *                         the cap is derived from [contextBudget.ragTokens] if a
     *                         live budget is available, or [DEFAULT_MAX_RAG_TOKENS] otherwise.
     * @param extraContext     Any additional context the caller wants injected
     *                         (screen content, accessibility context, etc.).
     * @param contextBudget    Live budget from LlamaManager.contextBudget.
     *                         Defaults to [ContextBudget.UNLOADED] for backward compat.
     */
    fun build(
        agentModePrompt: String,
        responseStyle:   String          = "balanced",
        customPrompt:    String          = "",
        performanceMode: PerformanceMode = PerformanceMode.BALANCED,
        queryType:       QueryType       = QueryType.UNKNOWN,
        ragContextBlock: String          = "",
        memorySummary:   String          = "",
        skillBlock:      String          = "",
        toolBlock:       String          = "",
        maxRagTokens:    Int             = -1,
        extraContext:    String          = "",
        contextBudget:   ContextBudget   = ContextBudget.UNLOADED
    ): String {
        // SPRINT 1: Derive effective token caps from the live ContextBudget when available.
        // Explicit maxRagTokens overrides the budget (e.g. buildFast passes 128).
        val effectiveRagTokens: Int = when {
            maxRagTokens >= 0 -> maxRagTokens
            contextBudget.nCtx > ContextBudget.UNLOADED.nCtx -> contextBudget.ragTokens
            else -> DEFAULT_MAX_RAG_TOKENS
        }
        val effectiveSummaryChars: Int = when {
            contextBudget.nCtx > ContextBudget.UNLOADED.nCtx -> contextBudget.summaryChars
            else -> DEFAULT_MAX_RAG_TOKENS * CHARS_PER_TOKEN  // ~2048 chars
        }
        val sb = StringBuilder()

        // ── 1. Agent persona ────────────────────────────────────────────────────
        sb.append(agentModePrompt.trim())

        // ── 2. Memory compression summary (older turns) ─────────────────────────
        // SPRINT 1: char cap scales with contextBudget.summaryChars (was hardcoded 1_600).
        if (memorySummary.isNotBlank()) {
            sb.append("\n\n--- Conversation summary (older context) ---\n")
            sb.append(memorySummary.trim().take(effectiveSummaryChars))
            sb.append("\n--- End of summary ---")
        }

        // ── 3. RAG context block (semantic memory retrieval) ────────────────────
        // SPRINT 1: effectiveRagTokens derived from ContextBudget (was DEFAULT_MAX_RAG_TOKENS=512).
        val trimmedRag = trimToTokenBudget(ragContextBlock.trim(), effectiveRagTokens)
        if (trimmedRag.isNotBlank()) {
            sb.append("\n\n")
            sb.append(trimmedRag)
        }

        // ── 4. Extra context (screen / accessibility / caller-injected) ──────────
        // Phase B: cap sourced from ContributorBudgetPolicy.EXTRA_CONTEXT_MAX_CHARS.
        if (extraContext.isNotBlank()) {
            sb.append("\n\n--- Current context ---\n")
            sb.append(extraContext.trim().take(ContributorBudgetPolicy.EXTRA_CONTEXT_MAX_CHARS))
        }

        // ── 5. Response style hint ───────────────────────────────────────────────
        sb.append("\n")
        when (responseStyle) {
            "concise"  -> sb.append("\nKeep responses brief and to the point.")
            "detailed" -> sb.append("\nProvide detailed, comprehensive responses with examples where helpful.")
            else       -> sb.append("\nBalance detail and brevity.")
        }

        // ── 6. Performance-mode hint ─────────────────────────────────────────────
        when (performanceMode) {
            PerformanceMode.FAST    -> sb.append("\nRespond very concisely. 2-3 sentences max unless strictly required.")
            PerformanceMode.QUALITY -> sb.append("\nProvide thorough, well-structured answers with clear reasoning.")
            else                    -> Unit
        }

        // ── 7. Query-type hint ───────────────────────────────────────────────────
        when (queryType) {
            QueryType.SIMPLE     -> sb.append("\nSIMPLE query: answer in 1-2 sentences ONLY. Do not expand.")
            QueryType.ANALYTICAL -> sb.append("\nANALYTICAL: structure with clear reasoning. Stop when the point is made.")
            QueryType.ACTION     -> sb.append("\nACTION: deliver exactly what was requested. No commentary.")
            QueryType.CREATIVE   -> sb.append("\nCREATIVE: be imaginative. Dive straight into the creative content.")
            QueryType.UNKNOWN    -> Unit
        }

        // ── 8. Skill block (omitted in FAST mode for latency) ───────────────────
        if (performanceMode != PerformanceMode.FAST && skillBlock.isNotBlank()) {
            sb.append("\n\n")
            sb.append(skillBlock.trim())
        }

        // ── 9. Tool block (omitted in FAST mode) ─────────────────────────────────
        if (performanceMode != PerformanceMode.FAST && toolBlock.isNotBlank()) {
            sb.append("\n\n")
            sb.append(toolBlock.trim())
        }

        // ── 10. Quality rules ─────────────────────────────────────────────────────
        sb.append(QUALITY_RULES)

        // ── 11. User custom prompt override ──────────────────────────────────────
        if (customPrompt.isNotBlank()) {
            sb.append("\n")
            sb.append(customPrompt.trim())
        }

        val result = sb.toString()

        val ragToks     = estimateTokens(trimmedRag)
        val summaryToks = estimateTokens(memorySummary)
        val skillToks   = if (performanceMode != PerformanceMode.FAST) estimateTokens(skillBlock) else 0
        val toolToks    = if (performanceMode != PerformanceMode.FAST) estimateTokens(toolBlock) else 0
        val totalToks   = estimateTokens(result)

        Log.i(TAG,
            "AIRI PROMPT_BUILT totalTokens=$totalToks ragTokens=$ragToks " +
            "summaryTokens=$summaryToks skillTokens=$skillToks toolTokens=$toolToks " +
            "effectiveRagBudget=$effectiveRagTokens nCtx=${contextBudget.nCtx} " +
            "mode=${performanceMode.name} query=${queryType.name} " +
            "hasRag=${trimmedRag.isNotBlank()} hasSummary=${memorySummary.isNotBlank()}"
        )
        return result
    }

    /**
     * Lightweight variant for fast path / simple queries.
     * Omits skill/tool blocks and limits RAG to 128 tokens.
     */
    fun buildFast(
        agentModePrompt: String,
        ragContextBlock: String         = "",
        customPrompt:    String         = "",
        contextBudget:   ContextBudget  = ContextBudget.UNLOADED
    ): String = build(
        agentModePrompt = agentModePrompt,
        performanceMode = PerformanceMode.FAST,
        queryType       = QueryType.SIMPLE,
        ragContextBlock = ragContextBlock,
        customPrompt    = customPrompt,
        maxRagTokens    = 128,           // explicit override — fast path always caps at 128 tokens
        contextBudget   = contextBudget
    )

    // ── Context ranking ───────────────────────────────────────────────────────

    /**
     * Rank and merge multiple context blocks by relevance score.
     *
     * Input: list of (contextBlock, relevanceScore 0-1) pairs.
     * Output: a single merged block trimmed to [maxTokens], highest-relevance
     * blocks included first.
     *
     * Used when multiple retrieval passes (e.g. multi-query RAG) produce
     * overlapping results that need to be deduped and ranked before injection.
     */
    fun rankAndMergeContexts(
        contexts:  List<Pair<String, Float>>,
        maxTokens: Int = DEFAULT_MAX_RAG_TOKENS
    ): String {
        if (contexts.isEmpty()) return ""

        val sorted = contexts
            .filter { (block, _) -> block.isNotBlank() }
            .sortedByDescending { (_, score) -> score }

        val merged = StringBuilder()
        var usedTokens = 0

        for ((block, _) in sorted) {
            val blockTokens = estimateTokens(block)
            if (usedTokens + blockTokens > maxTokens) break
            merged.append(block.trim()).append("\n")
            usedTokens += blockTokens
        }

        return merged.toString().trim()
    }

    // ── Internal ──────────────────────────────────────────────────────────────

    private fun trimToTokenBudget(text: String, maxTokens: Int): String {
        if (text.isBlank() || maxTokens <= 0) return ""
        val maxChars = maxTokens * CHARS_PER_TOKEN
        return if (text.length <= maxChars) text else text.take(maxChars) + "\n[...trimmed]"
    }

    private fun estimateTokens(text: String): Int =
        if (text.isBlank()) 0 else (text.length + CHARS_PER_TOKEN - 1) / CHARS_PER_TOKEN

    private val QUALITY_RULES = """

STRICT RESPONSE RULES — follow every rule exactly:
1. Lead with the answer immediately. No preamble, no warm-up.
2. Be concise. One sentence for greetings, 2-3 sentences for simple facts.
3. Never use filler: no "Certainly!", "Of course!", "Sure!", "Great question!".
4. Stop writing as soon as the answer is complete. Do not pad or summarize.
5. If unsure, say so briefly. Never fabricate facts.
6. Do not repeat or rephrase the user's question in your reply.
7. Use bullet points only when listing 3 or more distinct items.
8. Match the exact language the user writes in (Arabic → Arabic, English → English).
9. Never apologize for being concise.
10. If asked for a single thing, give exactly one thing."""
}
