#!/usr/bin/env bash
# check_build_errors.sh
# Scans Android resource files for problems that cause build failures.
# READ-ONLY: reports issues, never modifies files.
# Usage: bash scripts/check_build_errors.sh

set -euo pipefail

RES_DIR="app/src/main/res"
FOUND=0

red()   { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow(){ printf '\033[33m%s\033[0m\n' "$*"; }
bold()  { printf '\033[1m%s\033[0m\n'  "$*"; }

bold "=== AIRI Android Build Error Scanner ==="
echo "Scanning: $RES_DIR"
echo ""

# ──────────────────────────────────────────────────────────────────────────────
# 1. Duplicate string names within each strings.xml file
# ──────────────────────────────────────────────────────────────────────────────
bold "── [1] Duplicate <string> names within each strings.xml ──"
while IFS= read -r file; do
  dups=$(grep -o 'name="[^"]*"' "$file" | sort | uniq -d)
  if [ -n "$dups" ]; then
    red "  FAIL $file"
    while IFS= read -r dup; do
      lines=$(grep -n "$dup" "$file" | awk -F: '{print $1}' | tr '\n' ',' | sed 's/,$//')
      echo "       duplicate $dup  (lines: $lines)"
    done <<< "$dups"
    FOUND=$((FOUND + 1))
  else
    green "  OK   $file"
  fi
done < <(find "$RES_DIR" -name "strings.xml" | sort)
echo ""

# ──────────────────────────────────────────────────────────────────────────────
# 2. Duplicate names in other value XML files (colors, dimens, styles, attrs)
# ──────────────────────────────────────────────────────────────────────────────
bold "── [2] Duplicate names in other values XML files ──"
while IFS= read -r file; do
  dups=$(grep -o 'name="[^"]*"' "$file" 2>/dev/null | sort | uniq -d)
  if [ -n "$dups" ]; then
    red "  FAIL $file"
    while IFS= read -r dup; do
      lines=$(grep -n "$dup" "$file" | awk -F: '{print $1}' | tr '\n' ',' | sed 's/,$//')
      echo "       duplicate $dup  (lines: $lines)"
    done <<< "$dups"
    FOUND=$((FOUND + 1))
  fi
done < <(find "$RES_DIR" -name "*.xml" ! -name "strings.xml" -path "*/values*" | sort)
COUNT=$(find "$RES_DIR" -name "*.xml" ! -name "strings.xml" -path "*/values*" | wc -l)
[ "$COUNT" -gt 0 ] && green "  Checked $COUNT non-strings values XML files" || echo "  (none found)"
echo ""

# ──────────────────────────────────────────────────────────────────────────────
# 3. Malformed XML (well-formedness check via xmllint if available)
# ──────────────────────────────────────────────────────────────────────────────
bold "── [3] XML well-formedness ──"
if command -v xmllint &>/dev/null; then
  while IFS= read -r file; do
    if ! xmllint --noout "$file" 2>/tmp/xmllint_err; then
      red "  FAIL $file"
      sed 's/^/       /' /tmp/xmllint_err
      FOUND=$((FOUND + 1))
    else
      green "  OK   $file"
    fi
  done < <(find "$RES_DIR" -name "*.xml" | sort)
else
  yellow "  SKIP xmllint not installed — install with: apt-get install libxml2-utils"
fi
echo ""

# ──────────────────────────────────────────────────────────────────────────────
# 4. strings.xml entries referenced in Kotlin but missing from values/strings.xml
#    (one-way check: finds R.string.FOO calls whose FOO is absent from base file)
#
#    AUTO-GENERATED EXCLUSIONS — these are injected at build time by Gradle
#    plugins and are never declared in strings.xml:
#      default_web_client_id  → generated by processGoogleServices from google-services.json
# ──────────────────────────────────────────────────────────────────────────────
bold "── [4] R.string references in Kotlin not found in base strings.xml ──"
BASE_STRINGS="$RES_DIR/values/strings.xml"
AUTOGENERATED_KEYS="default_web_client_id"
if [ -f "$BASE_STRINGS" ]; then
  missing=0
  while IFS= read -r key; do
    # skip known auto-generated keys injected by Gradle plugins at build time
    if echo "$AUTOGENERATED_KEYS" | grep -qw "$key"; then
      continue
    fi
    if ! grep -q "name=\"$key\"" "$BASE_STRINGS"; then
      yellow "  MISSING  R.string.$key  (used in Kotlin, not in base strings.xml)"
      missing=$((missing + 1))
      FOUND=$((FOUND + 1))
    fi
  done < <(grep -rh 'R\.string\.[a-zA-Z0-9_]*' app/src/main/java \
             --include="*.kt" -o \
           | grep -o '[a-zA-Z0-9_]*$' \
           | sort -u)
  [ "$missing" -eq 0 ] && green "  OK   all R.string references resolve"
else
  yellow "  SKIP base strings.xml not found at $BASE_STRINGS"
fi
echo ""

# ──────────────────────────────────────────────────────────────────────────────
# 5. Drawable / mipmap duplicate filenames (same name, different density bucket)
#    These don't cause mergeResources failures but catch shadowing issues early.
# ──────────────────────────────────────────────────────────────────────────────
bold "── [5] Drawable filename conflicts across density buckets ──"
dup_drawables=$(find "$RES_DIR" -type f \( -name "*.png" -o -name "*.xml" -o -name "*.webp" \) \
  ! -path "*/values*" \
  | xargs -I{} basename {} \
  | sort | uniq -d)
if [ -n "$dup_drawables" ]; then
  yellow "  NOTE  The following drawable filenames appear in multiple buckets (normal if intentional):"
  while IFS= read -r name; do
    buckets=$(find "$RES_DIR" -name "$name" ! -path "*/values*" | sed "s|$RES_DIR/||" | tr '\n' '  ')
    echo "         $name  →  $buckets"
  done <<< "$dup_drawables"
else
  green "  OK   no drawable filename conflicts"
fi
echo ""

# ──────────────────────────────────────────────────────────────────────────────
# Summary
# ──────────────────────────────────────────────────────────────────────────────
bold "── Summary ──"
if [ "$FOUND" -eq 0 ]; then
  green "All checks passed — no build-blocking resource errors found."
else
  red "$FOUND problem(s) found — fix the items above before running ./gradlew assembleDebug."
  exit 1
fi
