from pathlib import Path

root = Path("skills")
programming = {
    "debugging": ("Debugging Assistant", "Localize defects from supplied symptoms, logs, and reproductions.", "a bug report, stack trace, or minimal reproduction", "root-cause candidates, evidence gaps, a regression guard", "Use when a software failure needs structured diagnosis. Do not use as proof without a reproducible case."),
    "test_generation": ("Test Generation", "Generate focused tests from behavior and contracts.", "source code, requirements, and expected behavior", "unit or integration test cases, fixtures, expected outcomes", "Use when behavior is known but coverage is missing. Review generated tests before adoption."),
    "unit_test_analysis": ("Unit Test Analysis", "Evaluate assertions, isolation, boundary coverage, and brittleness.", "unit tests and the code under test", "prioritized quality findings and test improvements", "Use to improve test quality; do not treat coverage percentage as correctness proof."),
    "dependency_analysis": ("Dependency Analysis", "Analyze dependency roles, coupling, conflicts, and upgrade risk.", "dependency manifests and usage evidence", "dependency map, risks, and conservative upgrade or cleanup plan", "Use before upgrades or cleanup. It does not resolve packages or certify licenses without supplied metadata."),
    "api_integration": ("API Integration Planner", "Design safe API adapters and explicit request/response contracts.", "API documentation, client requirements, and auth constraints", "schemas, retry/error/idempotency plan, and contract tests", "Use before implementing an integration. It never calls an external API or stores credentials."),
    "git_workflow": ("Git Workflow Assistant", "Plan safe branches, commits, reviews, and rollback boundaries.", "repository state and change intent", "small commit sequence, review gates, and safe rollback commands", "Use to organize changes. It does not execute Git commands or push branches."),
    "repository_analysis": ("Repository Analysis", "Map modules, entry points, boundaries, and change hotspots.", "repository tree and supplied source metadata", "evidence-linked architecture map and investigation plan", "Use with an exported tree or repository files; it cannot inspect unavailable files."),
    "error_log_analysis": ("Error Log Analysis", "Normalize error signatures and probable causes from logs.", "redacted logs with timestamps and context", "triage table, evidence gaps, and safe diagnostic collection", "Use after removing credentials and personal data from logs."),
    "documentation_generation": ("Documentation Generation", "Generate maintainable technical documentation from contracts and source.", "source contracts, examples, and intended audience", "structured documentation, limitations, and update triggers", "Use when documentation is missing; it cannot prove behavior absent from supplied evidence."),
}
security = {
    "security_code_review": ("Security Code Review", "Review source for defensive security weaknesses and safer alternatives.", "source code and security-sensitive data flows", "findings, secure changes, regression tests, and safe validation", "Use for authorized code review. Never use to generate exploit payloads or bypass instructions."),
    "vulnerability_analysis": ("Vulnerability Analysis", "Classify vulnerability evidence and prioritize remediation.", "vulnerability report or code evidence", "risk treatment, remediation, detection, and authorized validation", "Use for defensive assessment only. No exploitation, scanning, or payload generation."),
    "dependency_vulnerability_check": ("Dependency Vulnerability Check", "Review supplied dependency versions against advisory evidence.", "dependency manifest and advisory evidence", "affected-version assessment, mitigation, upgrade plan, and verification", "Use with supplied advisory data; it does not query registries or claim current CVE status."),
    "secure_configuration_review": ("Secure Configuration Review", "Review application and infrastructure configuration for secure defaults.", "redacted configuration and deployment context", "least-privilege remediation and non-invasive configuration tests", "Use for authorized configuration review. Never connect to infrastructure or expose secrets."),
    "owasp_analysis": ("OWASP Analysis", "Map supplied application behavior to defensive OWASP-style risks.", "application flow, code, and control evidence", "risk mapping, controls, secure changes, and authorized test cases", "Use as a review aid, not as penetration testing or certification."),
    "incident_triage": ("Incident Triage", "Prioritize a reported security incident and define safe first response.", "incident report, timeline, and affected assets", "severity, containment priorities, escalation, and evidence preservation", "Use for authorized response planning. It does not isolate hosts or execute response actions."),
    "security_log_analysis": ("Security Log Analysis", "Analyze security-relevant logs for defensive signals and telemetry gaps.", "redacted security logs and event context", "defensive findings, detection ideas, containment suggestions", "Use with privacy-preserving logs; never include credentials or unnecessary personal data."),
    "ioc_analysis": ("IOC Analysis", "Normalize and assess indicators of compromise defensively.", "indicators and provenance", "type, confidence, age, context, containment, and safe retrospective checks", "Use for defensive analysis. It does not scan, beacon, detonate, or contact indicators."),
    "malware_report_analysis": ("Malware Report Analysis", "Summarize malware reports into behaviors and defender mitigations.", "malware report and supplied observations", "behaviors, impact, containment, recovery, and detection recommendations", "Use for defensive reporting. It does not generate malware or provide evasion steps."),
    "security_documentation": ("Security Documentation", "Generate threat-aware security runbooks and control documentation.", "security design, controls, and audience", "runbook, prerequisites, evidence handling, escalation, and rollback", "Use to document approved procedures; documentation does not grant access."),
    "ctf_lab_assistant": ("CTF and Lab Assistant", "Support authorized educational labs with safe explanations and remediation.", "explicitly authorized lab prompt and scope", "lab-safe learning plan, hints, and defensive explanation", "Use only in sandbox or explicitly authorized labs; never real-target exploitation or persistence."),
    "network_security_analysis": ("Network Security Analysis", "Review supplied network designs, flows, and alerts defensively.", "network diagram, flow, or alert evidence", "trust-boundary findings, segmentation, monitoring, and hardening", "Use for authorized design review. It does not scan hosts, enumerate targets, or generate attack traffic."),
    "security_testing_planner": ("Security Testing Planner", "Plan bounded, authorized, non-destructive security tests.", "scope, authorization, objectives, and risk constraints", "test plan, safety gates, stop conditions, and remediation outputs", "Use before approved testing; authorization must be verified outside the model."),
    "privacy_security_audit": ("Privacy and Security Audit", "Audit data flows, minimization, retention, access, and controls.", "data flow, storage, permissions, and policy evidence", "privacy-preserving remediation and audit-ready verification", "Use as an engineering audit aid, not legal advice or certification."),
}

header = """# {name}\n\n## Description\n{description}\n\n## Purpose\nThis built-in AIRI skill performs evidence-first analysis through `DefensiveEngineeringSkill`. It does not claim to execute code, access repositories, contact services, or produce measurements that were not supplied.\n\n## When to use\nUse it when the supplied material matches the declared input and the user needs a structured, reviewable result.\n\n## When not to use\nDo not use it as a substitute for a real build, profiler, debugger, incident commander, legal review, or authorized security process.\n\n## Required tools\nThe skill requires only the active AIRI model bridge. It exposes no dangerous tool and performs no direct side effect.\n\n## Inputs\n{inputs}\n\n## Outputs\n{outputs}\n\n## Execution flow\n1. Inventory supplied evidence and mark unknowns.\n2. Analyze findings with severity, confidence, and evidence references.\n3. Produce incremental actions and deterministic verification guidance.\n\n## Security considerations\n{security}\n\n## Limitations\n{limitations}\n\n## Related skills\nUse the existing registry to compose this skill with repository, research, testing, documentation, or result-verification skills when their evidence is available.\n\n## Version\n1.0.0\n"""

for category, entries in (("programming", programming), ("cybersecurity", security)):
    for skill_id, (name, description, inputs, outputs, limitation) in entries.items():
        security_note = ("This is defensive and analysis-only. It must not scan, exploit, persist, evade, exfiltrate, or target systems. Provide remediation, detection, containment, lab-safe validation, or authorized planning only."
                         if category == "cybersecurity" else
                         "Keep changes reviewable and reversible. Never claim execution, compilation, test, or repository results without evidence.")
        path = root / category / skill_id / "SKILL.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(header.format(name=name, description=description, inputs=inputs, outputs=outputs, security=security_note, limitations=limitation), encoding="utf-8")

print(f"generated {len(programming) + len(security)} skill documents")
